all: exceptions.exe Misexcepciones.exe

exceptions.exe: main.cpp exceptions.cpp
	c++ -o exceptions.exe .\main.cpp .\exceptions.cpp

Misexcepciones.exe: Misexcepciones.cpp
	c++ -o Misexcepciones.exe Misexcepciones.cpp