all: bubbleSort.exe insertionSort.exe quickSort.exe selectionSort.exe

bubbleSort.exe: bubbleSort.cpp
	c++ -o bubbleSort.exe bubbleSort.cpp


insertionSort.exe: insertionSort.cpp
	c++ -o insertionSort.exe insertionSort.cpp

quickSort.exe: quickSort.cpp
	c++ -o quickSort.exe quickSort.cpp


selectionSort.exe: selectionSort.cpp
	c++ -o selectionSort.exe selectionSort.cpp